// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjxbvsodatbxaswmiol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuanhidnNvZGF0Ynhhc3dtaW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTM0ODIsImV4cCI6MjA2MTc4OTQ4Mn0.cH4bWWKpDelg6R8OC7E4ytjjALRuIDuS-AHa4Y5gK90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);